# Generated by Django 5.1 on 2024-09-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_created_at_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="archive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
