# Generated by Django 5.1 on 2024-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("EMPLOYEE", "Employee"),
                    ("CUSTOMER", "Customer"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
